#pragma once
#include <unordered_map>
#include <string>
#include <optional>

namespace KnownVariables {

struct ValueEntry {
    std::optional<std::string> unit;
    std::optional<short> decimals;

    // Default
    ValueEntry() = default;

    // Construct with optionals
    ValueEntry(std::optional<std::string> u, std::optional<short> d)
        : unit(std::move(u)), decimals(d) {}

    // Construct with raw values
    ValueEntry(const std::string& u, short d)
        : unit(u), decimals(d) {}
};

inline static const std::unordered_map<std::string, ValueEntry> kMap = {
    { "ACCELERATION BODY X", ValueEntry("meter per second squared", 2) },
    { "ACCELERATION BODY Y", ValueEntry("meter per second squared", 2) },
    { "ACCELERATION BODY Z", ValueEntry("meter per second squared", 2) },
    { "ACCELERATION WORLD X", ValueEntry("meter per second squared", 2) },
    { "ACCELERATION WORLD Y", ValueEntry("meter per second squared", 2) },
    { "ACCELERATION WORLD Z", ValueEntry("meter per second squared", 2) },
    { "GENERAL ENG RPM:1", ValueEntry("Rpm", 1) },
    { "GENERAL ENG RPM:2", ValueEntry("Rpm", 1) },
    { "GENERAL ENG RPM:3", ValueEntry("Rpm", 1) },
    { "GENERAL ENG RPM:4", ValueEntry("Rpm", 1) },
    { "GENERAL ENG THROTTLE LEVER POSITION:1", ValueEntry("Percent", 2) },
    { "GENERAL ENG THROTTLE LEVER POSITION:2", ValueEntry("Percent", 2) },
    { "GENERAL ENG THROTTLE LEVER POSITION:3", ValueEntry("Percent", 2) },
    { "GENERAL ENG THROTTLE LEVER POSITION:4", ValueEntry("Percent", 2) },
    { "GENERAL ENG MIXTURE LEVER POSITION:1", ValueEntry("Percent", 2) },
    { "GENERAL ENG MIXTURE LEVER POSITION:2", ValueEntry("Percent", 2) },
    { "GENERAL ENG MIXTURE LEVER POSITION:3", ValueEntry("Percent", 2) },
    { "GENERAL ENG MIXTURE LEVER POSITION:4", ValueEntry("Percent", 2) },
    { "GENERAL ENG PROPELLER LEVER POSITION:1", ValueEntry("Percent", 2) },
    { "GENERAL ENG PROPELLER LEVER POSITION:2", ValueEntry("Percent", 2) },
    { "GENERAL ENG PROPELLER LEVER POSITION:3", ValueEntry("Percent", 2) },
    { "GENERAL ENG PROPELLER LEVER POSITION:4", ValueEntry("Percent", 2) },
    { "GENERAL ENG EXHAUST GAS TEMPERATURE:1", ValueEntry("Celsius", 0) },
    { "GENERAL ENG EXHAUST GAS TEMPERATURE:2", ValueEntry("Celsius", 0) },
    { "GENERAL ENG EXHAUST GAS TEMPERATURE:3", ValueEntry("Celsius", 0) },
    { "GENERAL ENG EXHAUST GAS TEMPERATURE:4", ValueEntry("Celsius", 0) },
    { "GENERAL ENG FUEL PRESSURE:1", ValueEntry("Psi", 0) },
    { "GENERAL ENG FUEL PRESSURE:2", ValueEntry("Psi", 0) },
    { "GENERAL ENG FUEL PRESSURE:3", ValueEntry("Psi", 0) },
    { "GENERAL ENG FUEL PRESSURE:4", ValueEntry("Psi", 0) },
    { "GENERAL ENG FUEL USED SINCE START", ValueEntry("Pounds", 2) },
    { "ENG MAX RPM", ValueEntry("Rpm", 1) },
    { "ENG FUEL FLOW GPH:1", ValueEntry("Gallons per hour", 0) },
    { "ENG FUEL FLOW GPH:2", ValueEntry("Gallons per hour", 0) },
    { "ENG FUEL FLOW GPH:3", ValueEntry("Gallons per hour", 0) },
    { "ENG FUEL FLOW GPH:4", ValueEntry("Gallons per hour", 0) },
    { "ENG FUEL FLOW PPH:1", ValueEntry("Pounds per hour", 0) },
    { "ENG FUEL FLOW PPH:2", ValueEntry("Pounds per hour", 0) },
    { "ENG FUEL FLOW PPH:3", ValueEntry("Pounds per hour", 0) },
    { "ENG FUEL FLOW PPH:4", ValueEntry("Pounds per hour", 0) },
    { "TURB ENG CORRECTED N1:1", ValueEntry("Percent", 0) },
    { "TURB ENG CORRECTED N1:2", ValueEntry("Percent", 0) },
    { "TURB ENG CORRECTED N1:3", ValueEntry("Percent", 0) },
    { "TURB ENG CORRECTED N1:4", ValueEntry("Percent", 0) },
    { "TURB ENG CORRECTED N2:1", ValueEntry("Percent", 0) },
    { "TURB ENG CORRECTED N2:2", ValueEntry("Percent", 0) },
    { "TURB ENG CORRECTED N2:3", ValueEntry("Percent", 0) },
    { "TURB ENG CORRECTED N2:4", ValueEntry("Percent", 0) },
    { "TURB ENG ITT:1", ValueEntry("Celsius", 0) },
    { "TURB ENG ITT:2", ValueEntry("Celsius", 0) },
    { "TURB ENG ITT:3", ValueEntry("Celsius", 0) },
    { "TURB ENG ITT:4", ValueEntry("Celsius", 0) },
    { "TURB ENG AFTERBURNER PCT ACTIVE", ValueEntry("Percent", 0) },
    { "FUEL TANK CENTER LEVEL", ValueEntry("Percent", 0) },
    { "FUEL TANK CENTER2 LEVEL", ValueEntry("Percent", 0) },
    { "FUEL TANK CENTER3 LEVEL", ValueEntry("Percent", 0) },
    { "FUEL TANK LEFT MAIN LEVEL", ValueEntry("Percent", 0) },
    { "FUEL TANK LEFT AUX LEVEL", ValueEntry("Percent", 0) },
    { "FUEL TANK LEFT TIP LEVEL", ValueEntry("Percent", 0) },
    { "FUEL TANK RIGHT MAIN LEVEL", ValueEntry("Percent", 0) },
    { "FUEL TANK RIGHT AUX LEVEL", ValueEntry("Percent", 0) },
    { "FUEL TANK RIGHT TIP LEVEL", ValueEntry("Percent", 0) },
    { "FUEL TANK EXTERNAL1 LEVEL", ValueEntry("Percent", 0) },
    { "FUEL TANK EXTERNAL2 LEVEL", ValueEntry("Percent", 0) },
    { "FUEL TANK CENTER CAPACITY", ValueEntry("Gallons", 2) },
    { "FUEL TANK CENTER2 CAPACITY", ValueEntry("Gallons", 2) },
    { "FUEL TANK CENTER3 CAPACITY", ValueEntry("Gallons", 2) },
    { "FUEL TANK LEFT MAIN CAPACITY", ValueEntry("Gallons", 2) },
    { "FUEL TANK LEFT AUX CAPACITY", ValueEntry("Gallons", 2) },
    { "FUEL TANK LEFT TIP CAPACITY", ValueEntry("Gallons", 2) },
    { "FUEL TANK RIGHT MAIN CAPACITY", ValueEntry("Gallons", 2) },
    { "FUEL TANK RIGHT AUX CAPACITY", ValueEntry("Gallons", 2) },
    { "FUEL TANK RIGHT TIP CAPACITY", ValueEntry("Gallons", 2) },
    { "FUEL TANK EXTERNAL1 CAPACITY", ValueEntry("Gallons", 2) },
    { "FUEL TANK EXTERNAL2 CAPACITY", ValueEntry("Gallons", 2) },
    { "FUEL LEFT CAPACITY", ValueEntry("Gallons", 2) },
    { "FUEL RIGHT CAPACITY", ValueEntry("Gallons", 2) },
    { "FUEL TANK CENTER QUANTITY", ValueEntry("Gallons", 2) },
    { "FUEL TANK CENTER2 QUANTITY", ValueEntry("Gallons", 2) },
    { "FUEL TANK CENTER3 QUANTITY", ValueEntry("Gallons", 2) },
    { "FUEL TANK LEFT MAIN QUANTITY", ValueEntry("Gallons", 2) },
    { "FUEL TANK LEFT AUX QUANTITY", ValueEntry("Gallons", 2) },
    { "FUEL TANK LEFT TIP QUANTITY", ValueEntry("Gallons", 2) },
    { "FUEL TANK RIGHT MAIN QUANTITY", ValueEntry("Gallons", 2) },
    { "FUEL TANK RIGHT AUX QUANTITY", ValueEntry("Gallons", 2) },
    { "FUEL TANK RIGHT TIP QUANTITY", ValueEntry("Gallons", 2) },
    { "FUEL TANK EXTERNAL1 QUANTITY", ValueEntry("Gallons", 2) },
    { "FUEL TANK EXTERNAL2 QUANTITY", ValueEntry("Gallons", 2) },
    { "FUEL LEFT QUANTITY", ValueEntry("Gallons", 2) },
    { "FUEL RIGHT QUANTITY", ValueEntry("Gallons", 2) },
    { "FUEL TOTAL QUANTITY", ValueEntry("Gallons", 2) },
    { "FUEL WEIGHT PER GALLON", ValueEntry("Pounds", 2) },
    { "FUEL TOTAL CAPACITY", ValueEntry("Gallons", 2) },
    { "FUEL SELECTED QUANTITY PERCENT", ValueEntry("Percent", 2) },
    { "FUEL SELECTED QUANTITY", ValueEntry("Gallons", 2) },
    { "FUEL TOTAL QUANTITY WEIGHT", ValueEntry("Pounds", 2) },
    { "ESTIMATED FUEL FLOW", ValueEntry("Pounds per hour", 2) },
    { "GROUND VELOCITY", ValueEntry("Knots", 0) },
    { "TOTAL WORLD VELOCITY", ValueEntry("meter per second", 2) },
    { "VELOCITY BODY Z", ValueEntry("meter per second", 0) },
    { "VELOCITY BODY X", ValueEntry("meter per second", 0) },
    { "VELOCITY BODY Y", ValueEntry("meter per second", 0) },
    { "VELOCITY WORLD Z", ValueEntry("meter per second", 0) },
    { "VELOCITY WORLD X", ValueEntry("meter per second", 0) },
    { "VELOCITY WORLD Y", ValueEntry("meter per second", 0) },
    { "ROTATION VELOCITY BODY X", ValueEntry("meter per second", 2) },
    { "ROTATION VELOCITY BODY Y", ValueEntry("meter per second", 2) },
    { "ROTATION VELOCITY BODY Z", ValueEntry("meter per second", 2) },
    { "RELATIVE WIND VELOCITY BODY X", ValueEntry("meter per second", 2) },
    { "RELATIVE WIND VELOCITY BODY Y", ValueEntry("meter per second", 2) },
    { "RELATIVE WIND VELOCITY BODY Z", ValueEntry("meter per second", 2) },
    { "PLANE ALT ABOVE GROUND", ValueEntry("Feet", 2) },
    { "PLANE ALTITUDE", ValueEntry("Feet", 2) },
    { "MAGVAR", ValueEntry("Degrees", 0) },
    { "GROUND ALTITUDE", ValueEntry("Meters", 2) },
    { "AIRSPEED TRUE", ValueEntry("Knots", 0) },
    { "AIRSPEED INDICATED", ValueEntry("Knots", 0) },
    { "AIRSPEED TRUE CALIBRATE", ValueEntry("Degrees", 0) },
    { "AIRSPEED BARBER POLE", ValueEntry("Knots", 0) },
    { "AIRSPEED MACH", ValueEntry("Mach", 2) },
    { "VERTICAL SPEED", ValueEntry("Feet per minute", 0) },
    { "MACH MAX OPERATE", ValueEntry("Mach", 2) },
    { "BARBER POLE MACH", ValueEntry("Mach", 2) },
    { "INDICATED ALTITUDE", ValueEntry("Feet", 0) },
    { "KOHLSMAN SETTING MB", ValueEntry("Millibars", 0) },
    { "KOHLSMAN SETTING HG", ValueEntry("inHg", 2) },
    { "ATTITUDE BARS POSITION", ValueEntry("Percent", 0) },
    { "WISKEY COMPASS INDICATION DEGREES", ValueEntry("Degrees", 0) },
    { "RADIO HEIGHT", ValueEntry("Feet", 0) },
    { "MAX G FORCE", ValueEntry("Gforce", 2) },
    { "MIN G FORCE", ValueEntry("Gforce", 2) },
    { "SUCTION PRESSURE", ValueEntry("inHg", 2) },
    { "ADF CARD", ValueEntry("Degrees", 0) },
    { "HSI BEARING", ValueEntry("Degrees", 0) },
    { "HSI SPEED", ValueEntry("Knots", 0) },
    { "HSI DISTANCE", ValueEntry("Nautical miles", 2) },
    { "GPS POSITION LAT", ValueEntry("Degrees", 10) },
    { "GPS POSITION LON", ValueEntry("Degrees", 10) },
    { "GPS POSITION ALT", ValueEntry("Meters", 2) },
    { "GPS GROUND SPEED", ValueEntry("Meters per second", 2) },
    { "GPS WP DISTANCE", ValueEntry("Meters", 2) },
    { "GPS WP CROSS TRK", ValueEntry("Meters", 2) },
    { "GPS WP VERTICAL SPEED", ValueEntry("Meters per second", 2) },
    { "GPS ETE", ValueEntry("Seconds", 0) },
    { "GPS ETA", ValueEntry("Seconds", 0) },
    { "GPS WP NEXT LAT", ValueEntry("Degrees", 10) },
    { "GPS WP NEXT LON", ValueEntry("Degrees", 10) },
    { "GPS WP NEXT ALT", ValueEntry("Meters", 0) },
    { "GPS WP PREV LAT", ValueEntry("Degrees", 10) },
    { "GPS WP PREV LON", ValueEntry("Degrees", 10) },
    { "GPS WP PREV ALT", ValueEntry("Meters", 0) },
    { "GPS WP ETE", ValueEntry("Seconds", 0) },
    { "GPS WP ETA", ValueEntry("Seconds", 0) },
    { "GPS APPROACH TIMEZONE DEVIATION", ValueEntry("Seconds", 0) },
    { "GPS TARGET DISTANCE", ValueEntry("Meters", 2) },
    { "GPS TARGET ALTITUDE", ValueEntry("Meters", 2) },
    { "ELEVATOR TRIM POSITION", ValueEntry("Radians", 2) },
    { "ELEVATOR TRIM PCT", ValueEntry("Percent", 0) },
    { "SPOILERS HANDLE POSITION", ValueEntry("Position", 2) },
    { "SPOILERS LEFT POSITION", ValueEntry("Position", 2) },
    { "SPOILERS RIGHT POSITION", ValueEntry("Position", 2) },
    { "FLAPS HANDLE PERCENT", ValueEntry("Percent", 0) },
    { "TRAILING EDGE FLAPS LEFT PERCENT", ValueEntry("Percent", 0) },
    { "TRAILING EDGE FLAPS RIGHT PERCENT", ValueEntry("Percent", 0) },
    { "LEADING EDGE FLAPS LEFT PERCENT", ValueEntry("Percent", 0) },
    { "LEADING EDGE FLAPS RIGHT PERCENT", ValueEntry("Percent", 0) },
    { "AILERON LEFT DEFLECTION PCT", ValueEntry("Percent", 0) },
    { "AILERON RIGHT DEFLECTION PCT", ValueEntry("Percent", 0) },
    { "AILERON TRIM", ValueEntry("Radians", 2) },
    { "AILERON TRIM PCT", ValueEntry("Percent", 0) },
    { "RUDDER DEFLECTION PCT", ValueEntry("Percent", 0) },
    { "RUDDER TRIM PCT", ValueEntry("Percent", 0) },
    { "ELEVATOR DEFLECTION PCT", ValueEntry("Percent", 0) },
    { "AUTOPILOT HEADING LOCK DIR", ValueEntry("Degrees", 0) },
    { "AUTOPILOT HEADING LOCK DIR:1", ValueEntry("Degrees", 0) },
    { "AUTOPILOT ALTITUDE LOCK VAR", ValueEntry("Feet", 0) },
    { "AUTOPILOT ALTITUDE LOCK VAR:1", ValueEntry("Feet", 0) },
    { "AUTOPILOT ALTITUDE LOCK VAR:2", ValueEntry("Feet", 0) },
    { "AUTOPILOT ALTITUDE LOCK VAR:3", ValueEntry("Feet", 0) },
    { "AUTOPILOT VERTICAL HOLD VAR", ValueEntry("Feet/minute", 0) },
    { "AUTOPILOT VERTICAL HOLD VAR:1", ValueEntry("Feet/minute", 0) },
    { "AUTOPILOT VERTICAL HOLD VAR:2", ValueEntry("Feet/minute", 0) },
    { "AUTOPILOT VERTICAL HOLD VAR:3", ValueEntry("Feet/minute", 0) },
    { "AUTOPILOT AIRSPEED HOLD VAR", ValueEntry("Knots", 0) },
    { "AUTOPILOT AIRSPEED HOLD VAR:1", ValueEntry("Knots", 0) },
    { "AUTOPILOT AIRSPEED HOLD VAR:2", ValueEntry("Knots", 0) },
    { "GEAR HYDRAULIC PRESSURE", ValueEntry("Pound force per square foot (psf}", 2) },
    { "GEAR CENTER POSITION", ValueEntry("Percent", 0) },
    { "GEAR LEFT POSITION", ValueEntry("Percent", 0) },
    { "GEAR RIGHT POSITION", ValueEntry("Percent", 0) },
    { "GEAR TAIL POSITION", ValueEntry("Percent", 0) },
    { "GEAR AUX POSITION", ValueEntry("Percent", 0) },
    { "GEAR TOTAL PCT EXTENDED", ValueEntry("Percent", 0) },
    { "WATER RUDDER HANDLE POSITION", ValueEntry("Percent", 0) },
    { "WATER LEFT RUDDER EXTENDED", ValueEntry("Percentage", 0) },
    { "WATER RIGHT RUDDER EXTENDED", ValueEntry("Percentage", 0) },
    { "GEAR CENTER STEER ANGLE", ValueEntry("Percent", 0) },
    { "GEAR LEFT STEER ANGLE", ValueEntry("Percent", 0) },
    { "GEAR RIGHT STEER ANGLE", ValueEntry("Percent", 0) },
    { "GEAR AUX STEER ANGLE", ValueEntry("Percent", 0) },
    { "WATER LEFT RUDDER STEER ANGLE", ValueEntry("Percent", 0) },
    { "WATER RIGHT RUDDER STEER ANGLE", ValueEntry("Percent", 0) },
    { "GEAR CENTER STEER ANGLE PCT", ValueEntry("Percent", 0) },
    { "GEAR LEFT STEER ANGLE PCT", ValueEntry("Percent", 0) },
    { "GEAR RIGHT STEER ANGLE PCT", ValueEntry("Percent", 0) },
    { "GEAR AUX STEER ANGLE PCT", ValueEntry("Percent", 0) },
    { "WATER LEFT RUDDER STEER ANGLE PCT", ValueEntry("Percent", 0) },
    { "WATER RIGHT RUDDER STEER ANGLE PCT", ValueEntry("Percent", 0) },
    { "CENTER WHEEL RPM", ValueEntry("Rpm", 0) },
    { "LEFT WHEEL RPM", ValueEntry("Rpm", 0) },
    { "RIGHT WHEEL RPM", ValueEntry("Rpm", 0) },
    { "AUX WHEEL RPM", ValueEntry("Rpm", 0) },
    { "RETRACT LEFT FLOAT EXTENDED", ValueEntry("Percent", 0) },
    { "RETRACT RIGHT FLOAT EXTENDED", ValueEntry("Percent", 0) },
    { "STEER INPUT CONTROL", ValueEntry("Percent", 0) },
    { "AMBIENT DENSITY", ValueEntry("Slugs per cubic feet", 0) },
    { "AMBIENT TEMPERATURE", ValueEntry("Celsius", 2) },
    { "AMBIENT PRESSURE", ValueEntry("inHg", 2) },
    { "AMBIENT WIND VELOCITY", ValueEntry("Knots", 0) },
    { "AMBIENT WIND DIRECTION", ValueEntry("Degrees", 0) },
    { "AMBIENT WIND X", ValueEntry("Meters per second", 0) },
    { "AMBIENT WIND Y", ValueEntry("Meters per second", 0) },
    { "AMBIENT WIND Z", ValueEntry("Meters per second", 0) },
    { "STRUCT AMBIENT WIND", ValueEntry("Feet per second", 0) },
    { "AIRCRAFT WIND X", ValueEntry("Knots", 0) },
    { "AIRCRAFT WIND Y", ValueEntry("Knots", 0) },
    { "AIRCRAFT WIND Z", ValueEntry("Knots", 0) },
    { "BAROMETER PRESSURE", ValueEntry("Millibars", 0) },
    { "SEA LEVEL PRESSURE", ValueEntry("Millibars", 0) },
    { "TOTAL AIR TEMPERATURE", ValueEntry("Celsius", 2) },
    { "AMBIENT VISIBILITY", ValueEntry("Meters", 0) },
    { "STANDARD ATM TEMPERATURE", ValueEntry("Celsius", 0) },
    { "FOLDING WING LEFT PERCENT", ValueEntry("Percent", 0) },
    { "FOLDING WING RIGHT PERCENT", ValueEntry("Percent", 0) },
    { "CANOPY OPEN", ValueEntry("Percent", 0) },
    { "TAILHOOK POSITION", ValueEntry("Percent", 0) },
    { "ELECTRICAL TOTAL LOAD AMPS", ValueEntry("Amperes", 2) },
    { "ELECTRICAL BATTERY LOAD", ValueEntry("Amperes", 2) },
    { "ELECTRICAL BATTERY VOLTAGE", ValueEntry("Volts", 2) },
    { "ELECTRICAL MAIN BUS VOLTAGE", ValueEntry("Volts", 2) },
    { "ELECTRICAL MAIN BUS AMPS", ValueEntry("Amperes", 2) },
    { "ELECTRICAL AVIONICS BUS VOLTAGE", ValueEntry("Volts", 2) },
    { "ELECTRICAL AVIONICS BUS AMPS", ValueEntry("Amperes", 2) },
    { "ELECTRICAL HOT BATTERY BUS VOLTAGE", ValueEntry("Volts", 2) },
    { "ELECTRICAL HOT BATTERY BUS AMPS", ValueEntry("Amperes", 2) },
    { "ELECTRICAL BATTERY BUS VOLTAGE", ValueEntry("Volts", 2) },
    { "ELECTRICAL BATTERY BUS AMPS", ValueEntry("Amperes", 2) },
    { "ELECTRICAL BATTERY BUS CONTACT SWITCH", ValueEntry("Volts", 2) },
    { "HYDRAULIC SYSTEM INTEGRITY", ValueEntry("Percent", 0) },
    { "TOTAL WEIGHT", ValueEntry("Pounds", 0) },
    { "MAX GROSS WEIGHT", ValueEntry("Pounds", 0) },
    { "EMPTY WEIGHT", ValueEntry("Pounds", 0) },
    { "G FORCE", ValueEntry("GForce", 2) },
    { "DESIGN SPEED VS0", ValueEntry("Feet per second", 0) },
    { "DESIGN SPEED VS1", ValueEntry("Feet per second", 0) },
    { "DESIGN SPEED VC", ValueEntry("Feet per second", 0) },
    { "MIN DRAG VELOCITY", ValueEntry("Feet per second", 0) },
    { "ESTIMATED CRUISE SPEED", ValueEntry("Feet per second", 0) },
    { "CG PERCENT", ValueEntry("Percent", 0) },
    { "CG PERCENT LATERAL", ValueEntry("Percent", 0) },
    { "ATC SUGGESTED MIN RWY TAKEOFF", ValueEntry("Feet", 0) },
    { "ATC SUGGESTED MIN RWY LANDING", ValueEntry("Feet", 0) },
    { "TYPICAL DESCENT RATE", ValueEntry("Feet per minute", 0) },
    { "VISUAL MODEL RADIUS", ValueEntry("Meters", 2) },
    { "DYNAMIC PRESSURE", ValueEntry("Pounds per square foot", 0) },
    { "TOTAL VELOCITY", ValueEntry("Feet per second", 0) },
    { "AIRSPEED SELECT INDICATED OR TRUE", ValueEntry("Knots", 0) },
    { "VARIOMETER RATE", ValueEntry("Feet per second", 0) },
    { "PRESSURE ALTITUDE", ValueEntry("Meters", 0) },
    { "MAGNETIC COMPASS", ValueEntry("Degrees", 0) },
    { "BRAKE DEPENDENT HYDRAULIC PRESSURE", ValueEntry("Pounds per square foot", 2) },
    { "WING AREA", ValueEntry("Square feet", 2) },
    { "WING SPAN", ValueEntry("Feet", 2) },
    { "LINEAR CL ALPHA", ValueEntry("Per radian", 2) },
    { "CG AFT LIMIT", ValueEntry("Percent", 0) },
    { "CG FWD LIMIT", ValueEntry("Percent", 0) },
    { "CG MAX MACH", ValueEntry("Machs", 2) },
    { "CG MIN MACH", ValueEntry("Machs", 2) },
    { "EXIT POSX", ValueEntry("Feet", 2) },
    { "EXIT POSY", ValueEntry("Feet", 2) },
    { "EXIT POSZ", ValueEntry("Feet", 2) },
    { "DECISION HEIGHT", ValueEntry("Feet", 0) },
    { "DECISION ALTITUDE MSL", ValueEntry("Feet", 0) },
    { "EMPTY WEIGHT PITCH MOI", ValueEntry("Slugs per feet squared", 2) },
    { "EMPTY WEIGHT ROLL MOI", ValueEntry("Slugs per feet squared", 2) },
    { "EMPTY WEIGHT YAW MOI", ValueEntry("Slugs per feet squared", 2) },
    { "EMPTY WEIGHT CROSS COUPLED MOI", ValueEntry("Slugs per feet squared", 2) },
    { "TOTAL WEIGHT PITCH MOI", ValueEntry("Slugs per feet squared", 2) },
    { "TOTAL WEIGHT ROLL MOI", ValueEntry("Slugs per feet squared", 2) },
    { "TOTAL WEIGHT YAW MOI", ValueEntry("Slugs per feet squared", 2) },
    { "TOTAL WEIGHT CROSS COUPLED MOI", ValueEntry("Slugs per feet squared", 2) },
    { "MAX RATED ENGINE RPM", ValueEntry("Rpm", 0) },
    { "MANUAL FUEL PUMP HANDLE", ValueEntry("Percent", 0) },
    { "ELECTRICAL OLD CHARGING AMPS", ValueEntry("Amps", 2) },
    { "CONCORDE VISOR POSITION PERCENT", ValueEntry("Percent", 0) },
    { "PITOT ICE PCT", ValueEntry("Percent", 0) },
    { "SIMULATED RADIUS", ValueEntry("Feet", 0) },
    { "STRUCTURAL ICE PCT", ValueEntry("Percent", 0) },
    { "ARTIFICIAL GROUND ELEVATION", ValueEntry("Feet", 0) },
    { "PUSHBACK CONTACTX", ValueEntry("Feet", 2) },
    { "PUSHBACK CONTACTY", ValueEntry("Feet", 2) },
    { "PUSHBACK CONTACTZ", ValueEntry("Feet", 2) },
    { "YAW STRING PCT EXTENDED", ValueEntry("Percent", 0) },
    { "INDUCTOR COMPASS PERCENT DEVIATION", ValueEntry("Percent", 0) },
    { "ANEMOMETER PCT RPM", ValueEntry("Percent", 0) },
    { "NAV VOR LLAF64", ValueEntry("LLA structure", 0) },
    { "NAV GS LLAF64", ValueEntry("LLA structure", 0) },
    { "STATIC CG TO GROUND", ValueEntry("Feet", 2) },
    { "TOW RELEASE HANDLE", ValueEntry("Percent", 0) },
    { "APU PCT RPM", ValueEntry("Percent", 0) },
    { "APU PCT STARTER", ValueEntry("Percent", 0) },
    { "APU VOLTS", ValueEntry("Volts", 2) },
    { "PRESSURIZATION CABIN ALTITUDE", ValueEntry("Feet", 0) },
    { "PRESSURIZATION CABIN ALTITUDE GOAL", ValueEntry("Feet", 0) },
    { "PRESSURIZATION CABIN ALTITUDE RATE", ValueEntry("Feet per second", 0) },
    { "PRESSURIZATION PRESSURE DIFFERENTIAL", ValueEntry("Pounds per square foot", 0) },
    { "NAV ACTIVE FREQUENCY:1", ValueEntry("MHz", 2) },
    { "NAV STANDBY FREQUENCY:1", ValueEntry("MHz", 2) },
    { "NAV ACTIVE FREQUENCY:2", ValueEntry("MHz", 2) },
    { "NAV STANDBY FREQUENCY:2", ValueEntry("MHz", 2) },
    { "COM ACTIVE FREQUENCY:1", ValueEntry("MHz", 3) },
    { "COM STANDBY FREQUENCY:1", ValueEntry("MHz", 3) },
    { "COM ACTIVE FREQUENCY:2", ValueEntry("MHz", 3) },
    { "COM STANDBY FREQUENCY:2", ValueEntry("MHz", 3) },
    { "ADF ACTIVE FREQUENCY:1", ValueEntry("MHz", 0) },
    { "ADF STANDBY FREQUENCY:1", ValueEntry("MHz", 0) },
    { "ADF ACTIVE FREQUENCY:2", ValueEntry("MHz", 0) },
    { "ADF STANDBY FREQUENCY:2", ValueEntry("MHz", 0) },
    { "PLANE PITCH DEGREES", ValueEntry("Degrees", 2) },
    { "PLANE BANK DEGREES", ValueEntry("Degrees", 2) },
    { "PLANE HEADING DEGREES TRUE", ValueEntry("Degrees", 2) },
    { "PLANE HEADING DEGREES MAGNETIC", ValueEntry("Degrees", 2) },
    { "TURB ENG MAX TORQUE PERCENT:1", ValueEntry("Percent", 0) },
    { "TURB ENG MAX TORQUE PERCENT:2", ValueEntry("Percent", 0) },
    { "TURB ENG MAX TORQUE PERCENT:3", ValueEntry("Percent", 0) },
    { "TURB ENG MAX TORQUE PERCENT:4", ValueEntry("Percent", 0) },
    { "GENERAL ENG PCT MAX RPM:1", ValueEntry("Percent", 0) },
    { "GENERAL ENG PCT MAX RPM:2", ValueEntry("Percent", 0) },
    { "GENERAL ENG PCT MAX RPM:3", ValueEntry("Percent", 0) },
    { "GENERAL ENG PCT MAX RPM:4", ValueEntry("Percent", 0) },
    { "TURB ENG PRIMARY NOZZLE PERCENT:1", ValueEntry("Percent", 0) },
    { "TURB ENG PRIMARY NOZZLE PERCENT:2", ValueEntry("Percent", 0) },
    { "TURB ENG PRIMARY NOZZLE PERCENT:3", ValueEntry("Percent", 0) },
    { "TURB ENG PRIMARY NOZZLE PERCENT:4", ValueEntry("Percent", 0) },
    { "NAV OBS:1", ValueEntry("Degrees", 0) },
    { "NAV OBS:2", ValueEntry("Degrees", 0) },
    { "NAV DME:1", ValueEntry("Nautical miles", 1) },
    { "NAV DME:2", ValueEntry("Nautical miles", 1) },
    { "NAV DMESPEED:1", ValueEntry("Knots", 0) },
    { "NAV DMESPEED:2", ValueEntry("Knots", 0) },
    { "RECIP ENG COWL FLAP POSITION:1", ValueEntry("Percent", 2) },
    { "RECIP ENG COWL FLAP POSITION:2", ValueEntry("Percent", 2) },
    { "TURN COORDINATOR BALL", ValueEntry("Position 128", 0) },
    { "RECIP ENG MANIFOLD PRESSURE:1", ValueEntry("Psi", 0) },
    { "RECIP ENG MANIFOLD PRESSURE:2", ValueEntry("Psi", 0) },
    { "RECIP ENG MANIFOLD PRESSURE:3", ValueEntry("Psi", 0) },
    { "RECIP ENG MANIFOLD PRESSURE:4", ValueEntry("Psi", 0) },
    { "TURB ENG JET THRUST:1", ValueEntry("Pounds", 2) },
    { "TURB ENG JET THRUST:2", ValueEntry("Pounds", 2) },
    { "TURB ENG JET THRUST:3", ValueEntry("Pounds", 2) },
    { "TURB ENG JET THRUST:4", ValueEntry("Pounds", 2) },
    { "PROP THRUST:1", ValueEntry("Pounds", 2) },
    { "PROP THRUST:2", ValueEntry("Pounds", 2) },
    { "PROP THRUST:3", ValueEntry("Pounds", 2) },
    { "PROP THRUST:4", ValueEntry("Pounds", 2) },
    { "PROP RPM:1", ValueEntry("Rpm", 1) },
    { "PROP RPM:2", ValueEntry("Rpm", 1) },
    { "PROP RPM:3", ValueEntry("Rpm", 1) },
    { "PROP RPM:4", ValueEntry("Rpm", 1) },
    { "ENG CYLINDER HEAD TEMPERATURE:1", ValueEntry("Celsius", 0) },
    { "ENG CYLINDER HEAD TEMPERATURE:2", ValueEntry("Celsius", 0) },
    { "ENG CYLINDER HEAD TEMPERATURE:3", ValueEntry("Celsius", 0) },
    { "ENG CYLINDER HEAD TEMPERATURE:4", ValueEntry("Celsius", 0) },
    { "RECIP ENG CYLINDER HEAD TEMPERATURE:1", ValueEntry("Celsius", 0) },
    { "RECIP ENG CYLINDER HEAD TEMPERATURE:2", ValueEntry("Celsius", 0) },
    { "RECIP ENG CYLINDER HEAD TEMPERATURE:3", ValueEntry("Celsius", 0) },
    { "RECIP ENG CYLINDER HEAD TEMPERATURE:4", ValueEntry("Celsius", 0) },
    { "ENG OIL TEMPERATURE:1", ValueEntry("Celsius", 0) },
    { "ENG OIL TEMPERATURE:2", ValueEntry("Celsius", 0) },
    { "ENG OIL TEMPERATURE:3", ValueEntry("Celsius", 0) },
    { "ENG OIL TEMPERATURE:4", ValueEntry("Celsius", 0) },
    { "GENERAL ENG OIL TEMPERATURE:1", ValueEntry("Celsius", 0) },
    { "GENERAL ENG OIL TEMPERATURE:2", ValueEntry("Celsius", 0) },
    { "GENERAL ENG OIL TEMPERATURE:3", ValueEntry("Celsius", 0) },
    { "GENERAL ENG OIL TEMPERATURE:4", ValueEntry("Celsius", 0) },
    { "ENG OIL PRESSURE:1", ValueEntry("Psi", 0) },
    { "ENG OIL PRESSURE:2", ValueEntry("Psi", 0) },
    { "ENG OIL PRESSURE:3", ValueEntry("Psi", 0) },
    { "ENG OIL PRESSURE:4", ValueEntry("Psi", 0) },
    { "GENERAL ENG OIL PRESSURE:1", ValueEntry("Psi", 0) },
    { "GENERAL ENG OIL PRESSURE:2", ValueEntry("Psi", 0) },
    { "GENERAL ENG OIL PRESSURE:3", ValueEntry("Psi", 0) },
    { "GENERAL ENG OIL PRESSURE:4", ValueEntry("Psi", 0) },
    { "RECIP CARBURETOR TEMPERATURE:1", ValueEntry("Celsius", 0) },
    { "RECIP CARBURETOR TEMPERATURE:2", ValueEntry("Celsius", 0) },
    { "RECIP CARBURETOR TEMPERATURE:3", ValueEntry("Celsius", 0) },
    { "RECIP CARBURETOR TEMPERATURE:4", ValueEntry("Celsius", 0) },
    { "GYRO DRIFT ERROR", ValueEntry("Degrees", 0) },
    { "HEADING INDICATOR", ValueEntry("Degrees", 0) },
    { "THROTTLE LOWER LIMIT", ValueEntry("Percent", 2) },

    { "NUMBER OF ENGINES", ValueEntry() },
    { "MASTER IGNITION SWITCH", ValueEntry() },
    { "ENG COMBUSTION", ValueEntry() },
    { "GENERAL ENG COMBUSTION:1", ValueEntry() },
    { "GENERAL ENG COMBUSTION:2", ValueEntry() },
    { "GENERAL ENG COMBUSTION:3", ValueEntry() },
    { "GENERAL ENG COMBUSTION:4", ValueEntry() },
    { "GENERAL ENG MASTER ALTERNATOR:1", ValueEntry() },
    { "GENERAL ENG MASTER ALTERNATOR:2", ValueEntry() },
    { "GENERAL ENG FUEL PUMP SWITCH:1", ValueEntry() },
    { "GENERAL ENG FUEL PUMP SWITCH:2", ValueEntry() },
    { "GENERAL ENG FUEL PUMP SWITCH:3", ValueEntry() },
    { "GENERAL ENG FUEL PUMP SWITCH:4", ValueEntry() },
    { "GENERAL ENG FUEL PUMP SWITCH EX1:1", ValueEntry() },
    { "GENERAL ENG FUEL PUMP SWITCH EX1:2", ValueEntry() },
    { "GENERAL ENG FUEL PUMP SWITCH EX1:3", ValueEntry() },
    { "GENERAL ENG FUEL PUMP SWITCH EX1:4", ValueEntry() },
    { "GENERAL ENG FUEL PUMP ON:1", ValueEntry() },
    { "GENERAL ENG FUEL PUMP ON:2", ValueEntry() },
    { "GENERAL ENG FUEL PUMP ON:3", ValueEntry() },
    { "GENERAL ENG FUEL PUMP ON:4", ValueEntry() },
    { "GENERAL ENG STARTER:1", ValueEntry() },
    { "GENERAL ENG STARTER:2", ValueEntry() },
    { "GENERAL ENG STARTER:3", ValueEntry() },
    { "GENERAL ENG STARTER:4", ValueEntry() },
    { "GENERAL ENG GENERATOR SWITCH:1", ValueEntry() },
    { "GENERAL ENG GENERATOR SWITCH:2", ValueEntry() },
    { "GENERAL ENG GENERATOR SWITCH:3", ValueEntry() },
    { "GENERAL ENG GENERATOR SWITCH:4", ValueEntry() },
    { "GENERAL ENG GENERATOR ACTIVE:1", ValueEntry() },
    { "GENERAL ENG GENERATOR ACTIVE:2", ValueEntry() },
    { "GENERAL ENG GENERATOR ACTIVE:3", ValueEntry() },
    { "GENERAL ENG GENERATOR ACTIVE:4", ValueEntry() },
    { "GENERAL ENG ANTI ICE POSITION:1", ValueEntry() },
    { "GENERAL ENG ANTI ICE POSITION:2", ValueEntry() },
    { "GENERAL ENG ANTI ICE POSITION:3", ValueEntry() },
    { "GENERAL ENG ANTI ICE POSITION:4", ValueEntry() },
    { "GENERAL ENG FUEL VALVE:1", ValueEntry() },
    { "GENERAL ENG FUEL VALVE:2", ValueEntry() },
    { "GENERAL ENG FUEL VALVE:3", ValueEntry() },
    { "GENERAL ENG FUEL VALVE:4", ValueEntry() },
    { "GENERAL ENG STARTER ACTIVE", ValueEntry() },
    { "TURB ENG IGNITION ON", ValueEntry() },
    { "TURB ENG MASTER STARTER SWITCH", ValueEntry() },
    { "TURB ENG AFTERBURNER STAGE ACTIVE", ValueEntry() },
    { "FUEL TANK SELECTOR:1", ValueEntry() },
    { "FUEL TANK SELECTOR:2", ValueEntry() },
    { "FUEL TANK SELECTOR:3", ValueEntry() },
    { "FUEL TANK SELECTOR:4", ValueEntry() },
    { "FUEL TRANSFER PUMP ON:1", ValueEntry() },
    { "FUEL TRANSFER PUMP ON:2", ValueEntry() },
    { "FUEL TRANSFER PUMP ON:3", ValueEntry() },
    { "FUEL TRANSFER PUMP ON:4", ValueEntry() },
    { "NUM FUEL SELECTORS", ValueEntry() },
    { "UNLIMITED FUEL", ValueEntry() },
    { "LIGHT STROBE", ValueEntry() },
    { "LIGHT PANEL", ValueEntry() },
    { "LIGHT LANDING", ValueEntry() },
    { "LIGHT TAXI", ValueEntry() },
    { "LIGHT BEACON", ValueEntry() },
    { "LIGHT NAV", ValueEntry() },
    { "LIGHT LOGO", ValueEntry() },
    { "LIGHT WING", ValueEntry() },
    { "LIGHT RECOGNITION", ValueEntry() },
    { "LIGHT CABIN", ValueEntry() },
    { "LIGHT TAXI ON", ValueEntry() },
    { "LIGHT STROBE ON", ValueEntry() },
    { "LIGHT PANEL ON", ValueEntry() },
    { "LIGHT RECOGNITION ON", ValueEntry() },
    { "LIGHT WING ON", ValueEntry() },
    { "LIGHT LOGO ON", ValueEntry() },
    { "LIGHT CABIN ON", ValueEntry() },
    { "LIGHT CABIN ON:1", ValueEntry() },
    { "LIGHT CABIN ON:2", ValueEntry() },
    { "LIGHT CABIN ON:3", ValueEntry() },
    { "LIGHT CABIN ON:4", ValueEntry() },
    { "LIGHT HEAD ON", ValueEntry() },
    { "LIGHT BRAKE ON", ValueEntry() },
    { "LIGHT NAV ON", ValueEntry() },
    { "LIGHT BEACON ON", ValueEntry() },
    { "LIGHT LANDING ON", ValueEntry() },
    { "LIGHT PANEL POWER SETTING:1", ValueEntry() },
    { "LIGHT PANEL POWER SETTING:2", ValueEntry() },
    { "LIGHT PANEL POWER SETTING:3", ValueEntry() },
    { "LIGHT PANEL POWER SETTING:4", ValueEntry() },
    { "LIGHT CABIN POWER SETTING:1", ValueEntry() },
    { "LIGHT CABIN POWER SETTING:2", ValueEntry() },
    { "LIGHT CABIN POWER SETTING:3", ValueEntry() },
    { "LIGHT CABIN POWER SETTING:4", ValueEntry() },
    { "PROP DEICE SWITCH:1", ValueEntry() },
    { "PROP DEICE SWITCH:2", ValueEntry() },
    { "PROP DEICE SWITCH:3", ValueEntry() },
    { "PROP DEICE SWITCH:4", ValueEntry() },
    { "SIM ON GROUND", ValueEntry() },
    { "STALL WARNING", ValueEntry() },
    { "OVERSPEED WARNING", ValueEntry() },
    { "ATTITUDE CAGE", ValueEntry() },
    { "AVIONICS MASTER SWITCH", ValueEntry() },
    { "DME SOUND", ValueEntry() },
    { "TACAN DME SOUND", ValueEntry() },
    { "MARKER SOUND", ValueEntry() },
    { "INNER MARKER", ValueEntry() },
    { "MIDDLE MARKER", ValueEntry() },
    { "OUTER MARKER", ValueEntry() },
    { "HSI CDI NEEDLE", ValueEntry() },
    { "HSI GSI NEEDLE", ValueEntry() },
    { "HSI CDI NEEDLE VALID", ValueEntry() },
    { "HSI GSI NEEDLE VALID", ValueEntry() },
    { "HSI BEARING VALID", ValueEntry() },
    { "HSI HAS LOCALIZER", ValueEntry() },
    { "GPS IS ACTIVE FLIGHT PLAN", ValueEntry() },
    { "GPS IS ACTIVE WAY POINT", ValueEntry() },
    { "GPS IS ARRIVED", ValueEntry() },
    { "GPS IS DIRECTTO FLIGHTPLAN", ValueEntry() },
    { "GPS WP PREV VALID", ValueEntry() },
    { "GPS FLIGHT PLAN WP INDEX", ValueEntry() },
    { "GPS FLIGHT PLAN WP COUNT", ValueEntry() },
    { "GPS IS ACTIVE WP LOCKED", ValueEntry() },
    { "GPS IS APPROACH LOADED", ValueEntry() },
    { "GPS IS APPROACH ACTIVE", ValueEntry() },
    { "GPS APPROACH IS WP RUNWAY", ValueEntry() },
    { "GPS APPROACH APPROACH INDEX", ValueEntry() },
    { "GPS APPROACH TRANSITION INDEX", ValueEntry() },
    { "GPS APPROACH IS FINAL", ValueEntry() },
    { "GPS APPROACH IS MISSED", ValueEntry() },
    { "GPS APPROACH WP INDEX", ValueEntry() },
    { "GPS APPROACH WP COUNT", ValueEntry() },
    { "GPS DRIVES NAV1", ValueEntry() },
    { "COM RECIEVE ALL", ValueEntry() },
    { "COM RECEIVE ALL", ValueEntry() },
    { "COM TRANSMIT:1", ValueEntry() },
    { "COM TRANSMIT:2", ValueEntry() },
    { "COM STATUS:1", ValueEntry() },
    { "COM STATUS:2", ValueEntry() },
    { "COM AVAILABLE", ValueEntry() },
    { "COM TEST:1", ValueEntry() },
    { "COM TEST:2", ValueEntry() },
    { "ADF IDENT", ValueEntry() },
    { "ADF NAME", ValueEntry() },
    { "NAV IDENT", ValueEntry() },
    { "NAV NAME", ValueEntry() },
    { "TACAN IDENT", ValueEntry() },
    { "TACAN NAME", ValueEntry() },
    { "NAV GLIDE SLOPE", ValueEntry() },
    { "SELECTED DME", ValueEntry() },
    { "GPS WP NEXT ID", ValueEntry() },
    { "GPS WP PREV ID", ValueEntry() },
    { "BRAKE PARKING POSITION", ValueEntry() },
    { "BRAKE PARKING INDICATOR", ValueEntry() },
    { "SPOILERS ARMED", ValueEntry() },
    { "FLAPS HANDLE INDEX", ValueEntry() },
    { "FLAPS NUM HANDLE POSITIONS", ValueEntry() },
    { "FLAP DAMAGE BY SPEED", ValueEntry() },
    { "FLAP SPEED EXCEEDED", ValueEntry() },
    { "ALTERNATE STATIC SOURCE OPEN", ValueEntry() },
    { "FOLDING WING HANDLE POSITION", ValueEntry() },
    { "FUEL DUMP SWITCH", ValueEntry() },
    { "AUTOPILOT AVAILABLE", ValueEntry() },
    { "AUTOPILOT MASTER", ValueEntry() },
    { "AUTOPILOT DISENGAGED", ValueEntry() },
    { "AUTOPILOT NAV SELECTED", ValueEntry() },
    { "AUTOPILOT WING LEVELER", ValueEntry() },
    { "AUTOPILOT NAV1 LOCK", ValueEntry() },
    { "AUTOPILOT HEADING LOCK", ValueEntry() },
    { "AUTOPILOT HEADING SLOT INDEX", ValueEntry() },
    { "AUTOPILOT ALTITUDE LOCK", ValueEntry() },
    { "AUTOPILOT ALTITUDE SLOT INDEX", ValueEntry() },
    { "AUTOPILOT ATTITUDE HOLD", ValueEntry() },
    { "AUTOPILOT GLIDESLOPE HOLD", ValueEntry() },
    { "AUTOPILOT APPROACH HOLD", ValueEntry() },
    { "AUTOPILOT BACKCOURSE HOLD", ValueEntry() },
    { "AUTOPILOT PITCH HOLD", ValueEntry() },
    { "AUTOPILOT FLIGHT DIRECTOR ACTIVE", ValueEntry() },
    { "AUTOPILOT AIRSPEED HOLD", ValueEntry() },
    { "AUTOPILOT SPEED SLOT INDEX", ValueEntry() },
    { "AUTOPILOT FLIGHT LEVEL CHANGE", ValueEntry() },
    { "AUTOPILOT MACH HOLD", ValueEntry() },
    { "AUTOPILOT MACH HOLD VAR", ValueEntry() },
    { "AUTOPILOT YAW DAMPER", ValueEntry() },
    { "AUTOPILOT RPM HOLD VAR", ValueEntry() },
    { "AUTOPILOT THROTTLE ARM", ValueEntry() },
    { "AUTOPILOT TAKEOFF POWER ACTIVE", ValueEntry() },
    { "AUTOTHROTTLE ACTIVE", ValueEntry() },
    { "AUTOPILOT VERTICAL HOLD", ValueEntry() },
    { "AUTOPILOT RPM HOLD", ValueEntry() },
    { "FLY BY WIRE ELAC SWITCH", ValueEntry() },
    { "FLY BY WIRE FAC SWITCH", ValueEntry() },
    { "FLY BY WIRE SEC SWITCH", ValueEntry() },
    { "FLY BY WIRE ELAC FAILED", ValueEntry() },
    { "FLY BY WIRE FAC FAILED", ValueEntry() },
    { "FLY BY WIRE SEC FAILED", ValueEntry() },
    { "IS GEAR RETRACTABLE", ValueEntry() },
    { "IS GEAR SKIS", ValueEntry() },
    { "IS GEAR FLOATS", ValueEntry() },
    { "IS GEAR SKIDS", ValueEntry() },
    { "IS GEAR WHEELS", ValueEntry() },
    { "GEAR HANDLE POSITION", ValueEntry() },
    { "TAILWHEEL LOCK ON", ValueEntry() },
    { "AUTO BRAKE SWITCH CB", ValueEntry() },
    { "GEAR EMERGENCY HANDLE POSITION", ValueEntry() },
    { "ANTISKID BRAKES ACTIVE", ValueEntry() },
    { "RETRACT FLOAT SWITCH", ValueEntry() },
    { "GEAR DAMAGE BY SPEED", ValueEntry() },
    { "GEAR SPEED EXCEEDED", ValueEntry() },
    { "NOSEWHEEL LOCK ON", ValueEntry() },
    { "AMBIENT IN CLOUD", ValueEntry() },
    { "SMOKE ENABLE", ValueEntry() },
    { "PITOT HEAT", ValueEntry() },
    { "IS TAIL DRAGGER", ValueEntry() },
    { "ELECTRICAL MASTER BATTERY", ValueEntry() },
    { "ELECTRICAL MASTER BATTERY:1", ValueEntry() },
    { "ELECTRICAL MASTER BATTERY:2", ValueEntry() },
    { "ELECTRIC GPU ACTIVE", ValueEntry() },
    { "ELECTRIC GPU SWITCH", ValueEntry() },
    { "CIRCUIT GENERAL PANEL ON", ValueEntry() },
    { "CIRCUIT FLAP MOTOR ON", ValueEntry() },
    { "CIRCUIT GEAR MOTOR ON", ValueEntry() },
    { "CIRCUIT AUTOPILOT ON", ValueEntry() },
    { "CIRCUIT AVIONICS ON", ValueEntry() },
    { "CIRCUIT PITOT HEAT ON", ValueEntry() },
    { "CIRCUIT PROP SYNC ON", ValueEntry() },
    { "CIRCUIT AUTO FEATHER ON", ValueEntry() },
    { "CIRCUIT AUTO BRAKES ON", ValueEntry() },
    { "CIRCUIT STANDY VACUUM ON", ValueEntry() },
    { "CIRCUIT MARKER BEACON ON", ValueEntry() },
    { "CIRCUIT GEAR WARNING ON", ValueEntry() },
    { "CIRCUIT HYDRAULIC PUMP ON", ValueEntry() },
    { "STRUCTURAL DEICE SWITCH", ValueEntry() },
    { "APPLY HEAT TO SYSTEMS", ValueEntry() },
    { "IS USER SIM", ValueEntry() },
    { "LABEL SUPPORTED", ValueEntry() },
    { "SIM DISABLED", ValueEntry() },
    { "ATC HEAVY", ValueEntry() },
    { "AUTO COORDINATION", ValueEntry() },
    { "REALISM", ValueEntry() },
    { "TRUE AIRSPEED SELECTED", ValueEntry() },
    { "IS SLEW ACTIVE", ValueEntry() },
    { "IS SLEW ALLOWED", ValueEntry() },
    { "PAYLOAD STATION COUNT", ValueEntry() },
    { "USER INPUT ENABLED", ValueEntry() },
    { "CATEGORY", ValueEntry() },
    { "SIGMA SQRT", ValueEntry() },
    { "VARIOMETER SWITCH", ValueEntry() },
    { "TURN INDICATOR SWITCH", ValueEntry() },
    { "PANEL ANTI ICE SWITCH", ValueEntry() },
    { "PAYLOAD STATION NAME", ValueEntry() },
    { "WATER BALLAST VALVE", ValueEntry() },
    { "FULL THROTTLE THRUST TO WEIGHT RATIO", ValueEntry() },
    { "PROP AUTO CRUISE ACTIVE", ValueEntry() },
    { "DROPPABLE OBJECTS UI NAME", ValueEntry() },
    { "HYDRAULIC SWITCH", ValueEntry() },
    { "REALISM CRASH WITH OTHERS", ValueEntry() },
    { "REALISM CRASH DETECTION", ValueEntry() },
    { "MANUAL INSTRUMENT LIGHTS", ValueEntry() },
    { "RAD INS SWITCH", ValueEntry() },
    { "SURFACE INFO VALID", ValueEntry() },
    { "PUSHBACK WAIT", ValueEntry() },
    { "TOW CONNECTION", ValueEntry() },
    { "APU GENERATOR SWITCH", ValueEntry() },
    { "APU GENERATOR ACTIVE", ValueEntry() },
    { "APU ON FIRE DETECTED", ValueEntry() },
    { "PRESSURIZATION DUMP SWITCH", ValueEntry() },
    { "FIRE BOTTLE SWITCH", ValueEntry() },
    { "FIRE BOTTLE DISCHARGED", ValueEntry() },
    { "CABIN NO SMOKING ALERT SWITCH", ValueEntry() },
    { "CABIN SEATBELTS ALERT SWITCH", ValueEntry() },
    { "GPWS WARNING", ValueEntry() },
    { "GPWS SYSTEM ACTIVE", ValueEntry() },
    { "IS LATITUDE LONGITUDE FREEZE ON", ValueEntry() },
    { "IS ALTITUDE FREEZE ON", ValueEntry() },
    { "IS ATTITUDE FREEZE ON", ValueEntry() },
    { "ENG TORQUE:1", ValueEntry() },
    { "ENG TORQUE:2", ValueEntry() },
    { "ENG TORQUE:3", ValueEntry() },
    { "ENG TORQUE:4", ValueEntry() },
    { "TURB ENG FREE TURBINE TORQUE:1", ValueEntry() },
    { "TURB ENG FREE TURBINE TORQUE:2", ValueEntry() },
    { "TURB ENG FREE TURBINE TORQUE:3", ValueEntry() },
    { "TURB ENG FREE TURBINE TORQUE:4", ValueEntry() },
    { "TRANSPONDER CODE:1", ValueEntry() },
    { "TRANSPONDER STATE:1", ValueEntry() },
    { "NAV SOUND:1", ValueEntry() },
    { "NAV SOUND:2", ValueEntry() },
    { "SIMULATION RATE", ValueEntry() },
    { "COM SPACING MODE", ValueEntry() },
    { "ANGLE OF ATTACK INDICATOR", ValueEntry() },
    { "PLANE IN PARKING STATE", ValueEntry() },
    { "MASTER CAUTION ACTIVE", ValueEntry() },
    { "MASTER WARNING ACTIVE", ValueEntry() },
    { "MASTER CAUTION ACKNOWLEDGED", ValueEntry() },
    { "MASTER WARNING ACKNOWLEDGED", ValueEntry() },
    { "RECIP ENG LEFT MAGNETO:1", ValueEntry() },
    { "RECIP ENG LEFT MAGNETO:2", ValueEntry() },
    { "RECIP ENG LEFT MAGNETO:3", ValueEntry() },
    { "RECIP ENG LEFT MAGNETO:4", ValueEntry() },
    { "RECIP ENG RIGHT MAGNETO:1", ValueEntry() },
    { "RECIP ENG RIGHT MAGNETO:2", ValueEntry() },
    { "RECIP ENG RIGHT MAGNETO:3", ValueEntry() },
    { "RECIP ENG RIGHT MAGNETO:4", ValueEntry() },

    { "ABSOLUTE TIME", ValueEntry() },
    { "ZULU TIME", ValueEntry() },
    { "LOCAL TIME", ValueEntry() },
};


// Fallback helpers
inline std::string GetUnit(const std::string& name) {
    auto it = kMap.find(name);
    if (it != kMap.end() && it->second.unit)
        return it->second.unit.value();
    return "number";
}

inline int GetDecimals(const std::string& name) {
    auto it = kMap.find(name);
    if (it != kMap.end() && it->second.decimals)
        return it->second.decimals.value();
    return 0;
}

}  // namespace KnownVariables
